### ISSUE TITLE
Request: Support for React 19.0.0-rc

### ISSUE THREAD

**Issue by k-ardliyan** [justdlabs/icons#1]
Could you please update the JustD Labs Icons library to support React 19.0.0-rc? This is needed for projects experimenting with React RC in Next.js 15, ensuring compatibility and seamless integration. Thank you!

**Comment by irsyadadl** [comment]
@k-ardliyan [Release 1.7.9](https://github.com/justdlabs/icons/releases/tag/1.7.9)

**Comment by k-ardliyan** [comment]
Thank you @irsyadadl
